<html>
	<head>
		<title>Booking</title>
		<link rel = "stylesheet" type = "text/css" href ="view/form.css" >
	</head>
	
	<body>
		<div id=wrapper>
			<h1>List of bookings</h1>
			
			<p>
				Check if your booking is in the list.<br/>
				You can edit or delete your booking if needed.
			</p>
			
			<p>
				<?php require 'view/v_error.php'; ?>
				
				<?php
					//TABLE HEADER
					echo '<table>';
					echo '<tr>
							<th>ID</th>
							<th>Destination</th>
							<th>Insurance</th>
							<th>Price</th>
							<th>Passengers</th>
							<th>Functions</th>
						  </tr>';
						  
					//AUTOGENERATED ROWS
					while($row = $data->fetch_assoc())
					{
						$id = $row["ID"];
						$insurance = $row["insurance"]?"Yes":"No";
						$price = '$'.$row["price"];
						echo '<tr>
							<td>'.$id.'</td>
							<td>'.$row["destination"].'</td>
							<td>'.$insurance.'</td>
							<td>'.$price.'</td>';
						
						//PASSENGERS
						echo '<td>';
						
						$passengers = $db->getPassengers($id);
						while($pass = $passengers->fetch_assoc())
						{
							echo $pass["name"].' : '.$pass["age"].' years old';
							echo '</br>';
						}
						echo '</td>';
						
						//EDIT AND DELETE LINKS
						echo'<td>
								<a href=index.php?page=init&id='.$id.'>edit</a></br>
								<a href=index.php?page=delete&id='.$id.'>delete</a>
							</td>
						  </tr>';
					}
					
					//END OF TABLE
					echo '</table>';
				?>
				
				<a href=index.php?page=init><button type="button" class="normal">New Booking</button></a>
			</p>
		</div>
	</body>
	
</html>